name: Docker Image CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - 'ts.ini'
      - 'accs.db'
      - 'config.db'
      - 'qBittorrent.conf'
      - 'LICENSE'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
    - uses: actions/checkout@v3
    - id: string
      uses: ASzc/change-string-case-action@v5
      with:
        string: ${{ github.event.repository.name }}
    - run: echo "REPO_NAME=$(echo "${{ steps.string.outputs.lowercase }}")" >> $GITHUB_ENV
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2
    - name: Docker login
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - name: Build the Docker image
      run: docker buildx build . --push --file Dockerfile --tag $DOCKER_USERNAME/$REPO_NAME --platform linux/amd64,linux/arm64,linux/arm/v7
